name: Deploy MERN app to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      # Install backend dependencies
      - name: Install backend
        working-directory: ./backend
        run: npm install

      # Install frontend dependencies and build
      - name: Build Frontend
        working-directory: Frontend
        run: |
          npm install
          npm run build

      # ✅ Azure Login (fix for missing credentials)
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to Azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'gc-test' # your Azure app name
          package: ./backend
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
